import { poppins, akiraExpanded, robotoCondensed, firaCode } from "@libs/fonts";

import clsx from "clsx";

import { getServerSession } from "next-auth";

import "@styles/globals.css";

import { getCurrentUser } from "@api/users";

// import { authOptions } from '@api/auth/[...nextauth]/authOptions';

import {
  ThemeProvider,
  SessionProvider,
  TooltipProvider,
} from "@libs/providers";

import { CartProvider } from "@contexts/CartContext";
import { WishtlistProvider } from "@contexts/WishlistContext";
import { SidebarProvider } from "@contexts/SidebarContext";

import Toaster from "@components/ui/toaster";

import Navbar from "@components/navigations/navbar";
import Sidebar from "@components/navigations/sidebar";
import Footer from "@components/navigations/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: "rgb(230 220 100)",
};

export default async function RootLayout({ children }) {
  // const session = await getServerSession(authOptions);

  const currentUserData = await getCurrentUser();

  const bodyClasses = clsx(
    poppins.variable,
    akiraExpanded.variable,
    robotoCondensed.variable,
    firaCode.variable,
    "antialiased",
    "font-sans text-base leading-normal font-normal",
    "select-none overflow-x-hidden",
    "text-foreground bg-background"
  );

  return (
    <html lang="en">
      <body className={bodyClasses}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
        >
          <SessionProvider>
            <CartProvider>
              <WishtlistProvider>
                <TooltipProvider>
                  <SidebarProvider>
                    <Navbar currentUserData={currentUserData} />

                    <Sidebar currentUserData={currentUserData} />

                    {children}

                    <Footer />
                  </SidebarProvider>
                </TooltipProvider>
              </WishtlistProvider>
            </CartProvider>
          </SessionProvider>

          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
