import { poppins, robotoCondensed, firaCode } from "@libs/fonts";

import clsx from "clsx";

import "@styles/globals.css";

import { ThemeProvider, TooltipProvider } from "@libs/providers";

import { CartProvider } from "@contexts/CartContext";
import { WishtlistProvider } from "@contexts/WishlistContext";
import { SidebarProvider } from "@contexts/SidebarContext";

import Toaster from "@components/ui/toaster";

import Navbar from "@components/navigations/navbar";
// import Sidebar from "@components/navigations/sidebar";
import Footer from "@components/navigations/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: "rgb(0 0 0)",
};

export default function RootLayout({ children }) {
  const bodyClasses = clsx(
    poppins.variable,
    robotoCondensed.variable,
    firaCode.variable,
    "antialiased",
    "font-sans text-base leading-normal font-normal",
    "select-none overflow-x-hidden",
    "text-foreground bg-background"
  );

  return (
    <html lang="en">
      <body className={bodyClasses}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
        >
          <CartProvider>
            <WishtlistProvider>
              <TooltipProvider>
                <SidebarProvider>
                  <Navbar />

                  {/* <Sidebar /> */}

                  {children}

                  <Footer />
                </SidebarProvider>
              </TooltipProvider>
            </WishtlistProvider>
          </CartProvider>

          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
